### ISSUE TITLE
SMP-CCS development

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/tng-industrial-pilot#237]
This small auxiliary component intents to solve the problem that FSMs are not reachable from the outside making it hard to trigger manual reconfigurations, e.g., from the FMP. The idea is to run this small component next to the FMP. The FMP could access it using a REST API provided by the SDMP-CC. The FSM in turn connects to the SMP-CCS and opens a gRPC server stream connection. Using the the SMP-CCS can trigger actions in the FSM whenever it wants, still the FSM needs not to be reachable from outside. The only assumption here is that the FSM can reach the SMP-CCS, which can easily be realised, e.g., by hosting the SMP-CCS in the public Internet.

Code location: [tools/smp-ccs](https://github.com/sonata-nfv/tng-industrial-pilot/tree/master/tools/smp-ccs)
README and documentation: [here](https://github.com/sonata-nfv/tng-industrial-pilot/tree/master/tools/smp-ccs)

The SMP-CC is deployed at UPB's premises and reachable from the Internet:

* Host: fgcn-tango-smp-ctrl.cs.upb.de
* gRPC: 9012/TCP
* REST: 9011/TCP

```
curl -X GET fgcn-tango-smp-ctrl.cs.upb.de:9011/api/v1/ssmstatus
```

```
   {private}                        {public}
+------------+                 +-----------------+
|            |                 |     SMP-CC      |
|    FMP     |-----REST------->|(e.g. in Docker) |
|            |                 |                 |
+------------+                 +-----------------+
                                   ^        |
                                   |  (2) gRPC srv.
                                   |     stream
                               (1) gRPC     |
                                 req.       |
                                   |        |
                    + - - - - - - -|- - - - + - - - - - - - +
                                   |        v
                    |          +-----------------+          |
                               | +---------------+-+
                    |          +-+ +---------------+-+      |
                                 +-+       SSM       |
                    |              +-----------------+      |

                    |                                       |
                                 SONATA-NFV MANO
                    + - - - - - - - - - - - - - - - - - - - +
                                    {private}
```

Ports (e.g. fgcn-tango-vpn.cs.upb.de):
 * REST: 9011
 * gRPC: 9012 

See: https://github.com/sonata-nfv/tng-industrial-pilot/wiki/FSM-SSM-Development

---

## TODOs

- [x] setup basic code skeleton
- [x] implement basic gRPC examples
- [x] implement full gRPC interface and clients
- [x] allow PUT to update state of a give SSM (and multiple SSMs)
- [x] create example showing how to toggle the quarantaine
- [x] ensure that states are removed if SSM disconnects
- [x] make gRPC client robust and reconnect when something breaks
- [x] make gPRC client running in a separated thread (to move the code to the SSM)
- [x] package the server as docker and describe its usage
- [ ] integrate client into SSM
    - [x] when SSM starts, the SMP-CCC needs to register to the SMP-CCS
    - [x] test that SSM is deployed correctly with NS2 and that the trigger from the outside reaches it
    - [x] add logging of register events to server part for better monitoring
    - [x] when the SSM reconfigures because of the monitoring event, the SSM-wide state must be updated
    - [x] when a state update from the SMP-CCS arrives, the `configure_event` of the SSM needs to be triggered (implement SMP-CCC callback function)
        - [x] call callback method
        - [x] generate and send broker message that triggers the real configure_event
        - [x] test this in real infrastructure
    - [ ] skip reconfiguration when state is already set (_optional for first version_)
        - monitor trigger
        - manual trigger
    - [x] be able to reset quarantine state using the manual trigger 
        - [x] change FSM accordingly
        - [x] change SSM accordingly
        - [x] pass information from FSM to SSM `quarantine_state`
            - [x] BUG: SSM does always send `quarantine_state=Ture`
        - [x] test in real deployment
    - [ ] Optional: can we somehow send back state updates if SSM is triggered by monitoring? -> additional connection? bi-stream?
    - [x] do a full test
- [ ] integrate FMP to SMP-CCS

**Comment by mpeuster** [comment]
Notes from chat:

because that is the moment during instantiation that you know the service id
which you need for the topic to post the request on
you need to post on `"monitor.ssm.<service_intance_id>"`
And the payload needs to be a dict with two keys
workflow and reconfiguration_payload

```yaml
 ---
workflow: 'reconfigure'
reconfiguration_payload: 'whatever you want'
```

---

**Comment by mpeuster** [comment]
Testing workflow: https://github.com/sonata-nfv/tng-industrial-pilot/wiki/FSM-SSM-Development#deployingtesting

**Comment by mpeuster** [comment]
Open points are captured in dedicated issues:

- https://github.com/sonata-nfv/tng-industrial-pilot/issues/320
- https://github.com/sonata-nfv/tng-industrial-pilot/issues/319
- https://github.com/sonata-nfv/tng-industrial-pilot/issues/318
- https://github.com/sonata-nfv/tng-industrial-pilot/issues/317
