### ISSUE TITLE
Migrate Emulator Pilot to native K8s

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/tng-industrial-pilot#72]
This is an intermediate step before the pilot is deployed on K8s using 5GTANGO SP, we first want to have a version that is directly deployed on K8s without 5GTANGO.

## TODOs

See [corresponding wiki entry](https://github.com/sonata-nfv/tng-industrial-pilot/wiki/Deploying-the-service-on-Kubernetes)

- [x] adopt VNFs
  - [x] prepare Dockerfiles
  - [x] fix crashing CC processor (see https://github.com/sonata-nfv/tng-industrial-pilot/issues/89)
- [x] prepare K8s deployment descriptors
  - [x] Deployments for starting the containers
  - [x] Deployment of each CDU in a separate pod
  - [x] Services for accessing the containers (from outside, eg, for eae)
  - [x] Ingress for simplified external access? Or simply setting a fixed nodePort? Optional for now.
- [x] prepare service descriptors and figure out interconnection of CDUs
  - [x] Test connection from MDC to CC processor via CC broker using mosquitto CLI
  - [x] Integrate and tests all CNFs of NS1 and NS2 to work together
- [x] move DT outside of NS2 and k8s and connect to MDC from the outside
- [x] combine all CDUs of one CNF in one deployment and pod that's reachable through one k8s service
- [x] add new CC CDUs: Prometheus DB and exporter

**Comment by stefanbschneider** [comment]
Started working on deploying NS1 and NS2 on k8s: https://github.com/sonata-nfv/tng-industrial-pilot/wiki/Deploying-the-service-on-Kubernetes

To ensure all VNF containers keep running in k8s, they need a different `start.sh` than the vim-emu VNFs (that doesn't run the commands in background). I adjusted all relevant VNFs to use `start.vimemu.sh` for the `:vimemu` container and `start.sh` for `:k8s` (similar to `Dockerfile.vimemu` and `Dockerfile`). 

Once all VNFs run on k8s, the next step is to configure the networking and connection of the VNFs within k8s.

**Comment by stefanbschneider** [comment]
Currently, all pods are deployed fine at the beginning, but then keep crashing every now and then:

```bash
$ kubectl get pods
NAME                                 READY   STATUS             RESTARTS   AGE
sm-ns1-deployment-5564965dcc-n5d57   2/3     CrashLoopBackOff   13         76m
sm-ns2-deployment-67c8f6574f-9zb82   2/2     Running            0          76m
```

**Comment by stefanbschneider** [comment]
Connecting cc processor to cc broker within NS1 worked: Both are running inside the same pod and the processor can simply subscribe to the broker at localhost:1883 as before

Connecting the MDC in NS2 to the CC broker in NS1 doesn't work yet because they are running in different pods. Next time, I'll have to follow the debug guide [here](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/) to figure out what the problem is.
My current guess is that we need to change the service to `type: ClusterIP` (simply remove `type` because it's the default), but let's see.

**Comment by stefanbschneider** [comment]
Update: Put all containers/CDUs in separate pods such that they could be scaled independently.

For example: CC could have 3x Broker CDU and 5x Processor CDU and 1x DB CDU

**Comment by stefanbschneider** [comment]
Connection between containers works now (with microk8s DNS enabled). MQTT works also manually. Next update hard-coded IP addresses (e.g., in CC processor).

**Comment by stefanbschneider** [comment]
Next up: Move digital twin outside of NS2 and even outside of Kubernetes deployment. Start it outside as normal docker container trying to access the MDC running inside the k8s deployment. Similar to a real machine that would use NS2 from the outside.

Discuss with Manuel how to start in privileged mode such that the Samba file share works.

**Comment by stefanbschneider** [comment]
Started wiki page on how to deploy the DT as Docker container outside of K8s (and later also on how to connect it): https://github.com/sonata-nfv/tng-industrial-pilot/wiki/Connecting-the-digital-twin

*Note*: The Docker run command doesn't work on Windows for some reason. But works on Ubuntu.

**Comment by mpeuster** [comment]
CC CDU03 (mqttexporter) and CC CDU04 (prometheus DB) are ready to be picked up for the K8s deployment #92 

Still, I face some issues with DT, MDC in the vim-emu case. Might also happen in the K8s case #106

**Comment by stefanbschneider** [comment]
I figured out how to assign and expose fixed ports using k8s' `NodePort`: See updated [wiki page](https://github.com/sonata-nfv/tng-industrial-pilot/wiki/Connecting-the-digital-twin#nodeport-service).

Unfortunately, it still doesn't seem to work. The MDC still says "Error no EM63 response file was found! Retry!". 

Not sure if this is because the k8s service didn't work properly or due to some other problem. Also not sure how to debug.

*Wait:* I forgot to set the Samba host IP when starting the DT! By default this points to a fixed IP in the emulator. It should be `localhost` when running minikube locally? How to connect a Docker to the host machine's localhost: https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach

**Comment by stefanbschneider** [comment]
Updated todos above according to call and updated wiki page: https://github.com/sonata-nfv/tng-industrial-pilot/wiki/Integration-with-SP

**Comment by stefanbschneider** [comment]
Using a `NodePort` service and starting minikube with a custom port range works fine. But this doesn't seem to work for microk8s...

Workaround is to install a load balancer: 
[Microk8s-guide-V2.pdf](https://github.com/sonata-nfv/tng-industrial-pilot/files/2982396/Microk8s-guide-V2.pdf)
