### ISSUE TITLE
CC: Add Prometheus as edge database solution for sensor data to the CC

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/tng-industrial-pilot#92]
Prometheus seems to be a perfect fit for this sensor data use case at the edge.

Prometheus either pulls the metrics or needs a separated "pushgateway" to push data to it.

Design: Add a 4. CDU running the push Gateway. Let the CC processor push the metrics received on the broker to Prometheus.

* [vim-emu workflow](https://github.com/sonata-nfv/tng-industrial-pilot/wiki/Pilot-prototype-on-vim-emu)

## TODO

- [x] setup `:vimemu` Containers
- [x] run and test containers locally
- [x] push some metrics
- [x] re-test current state on vim-emu to check everything works
- [x] custom Prometheus container compatible to vim-emu
- [x] custom Pushgateway container compatible to vim-emu
- [x] update vim-emu descriptors and include CC.cdu04
- [x] update documentation figures
- [x] push metrics from CC processor (each sensor value is one metric)
- [x] run/integrate everything on vim-emu
  - [x] how to check if data arrives in Prometheus without accessing the web-interface? Fixed: https://github.com/sonata-nfv/son-emu/issues/295
- [x] redesign to have a MQTT subscriber that offers a prometheus data exporter
  - [x] replace PUSHGW by `mqttexporter`
  - [x] get MQTT messages
  - [x] export data to Prom.
  - [x] remove old code from CC processor
  - [x] update documentation (cdu03 = mqttex; cdu04=db)
- [x] increase prometheus scraping time? otherwise the sine curve is hard to see
- [x] check for stability -> #106 
- [x] extend vim-emu documentation with important commands for debugging etc. and explain how to check if everything works
- [x] ... migrate everything to the K8s service (reference this in #72 )

**Comment by mpeuster** [comment]
## Running Prometheus
* DB: https://prometheus.io/docs/prometheus/latest/installation/#using-docker
* PushGW: https://github.com/prometheus/pushgateway

```sh
docker run -p 9090:9090 sonatanfv/vnf-cc-database:vimemu
```

**Comment by mpeuster** [comment]
Next step: Parse MQTT messages correctly and push them to Prometheus

**Comment by mpeuster** [comment]
```
mosquitto_sub -h 127.0.0.1 -t WIMMS/EM63/#

mosquitto_pub -h 127.0.0.1 -p 1883 -t WIMMS/EM63/ArcTmp4a -m "250.4356"

```
